// state.go — Project Doppelgänger
//
// EngineState is the single source of truth for all runtime metrics.
// It is intentionally kept simple – a mutex-protected struct – so that
// it can be shared safely between the HTTP handlers and the browser
// automation goroutine without importing any additional packages.

package main

import (
	"sync"
	"time"
)

// EngineStatus represents the current lifecycle phase of the noise engine.
type EngineStatus string

const (
	StatusIdle    EngineStatus = "idle"
	StatusRunning EngineStatus = "running"
	StatusError   EngineStatus = "error"
)

// EngineState is thread-safe runtime state shared across the application.
type EngineState struct {
	mu sync.RWMutex

	// Status is the current lifecycle phase.
	Status EngineStatus

	// ActivePersona is the demographic description generated by the LLM
	// for the most recent (or currently running) session.
	ActivePersona string

	// ActiveQueries are the search strings for the current / last session.
	ActiveQueries []string

	// TotalQueriesInjected is the cumulative count of search queries that
	// have been fully executed since the server started.
	TotalQueriesInjected int

	// LastTriggerTime records when the most recent /trigger was received.
	LastTriggerTime time.Time

	// LastError stores the most recent error message (empty if none).
	LastError string
}

// NewEngineState returns an EngineState ready for use.
func NewEngineState() *EngineState {
	return &EngineState{
		Status: StatusIdle,
	}
}

// ---------------------------------------------------------------------------
// Thread-safe accessors / mutators
// ---------------------------------------------------------------------------

// SetRunning transitions into the running phase and stores the new persona.
func (s *EngineState) SetRunning(persona string, queries []string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.Status = StatusRunning
	s.ActivePersona = persona
	s.ActiveQueries = queries
	s.LastTriggerTime = time.Now()
	s.LastError = ""
}

// IncrementInjected increments the cumulative query counter by n.
func (s *EngineState) IncrementInjected(n int) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.TotalQueriesInjected += n
}

// SetIdle transitions back to idle after the browser session completes.
func (s *EngineState) SetIdle() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.Status = StatusIdle
}

// SetError records an error and transitions to the error phase.
func (s *EngineState) SetError(errMsg string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.Status = StatusError
	s.LastError = errMsg
}

// Snapshot returns an immutable view of the current state.
// Callers must not modify the returned value.
func (s *EngineState) Snapshot() StatusResponse {
	s.mu.RLock()
	defer s.mu.RUnlock()

	queries := make([]string, len(s.ActiveQueries))
	copy(queries, s.ActiveQueries)

	return StatusResponse{
		Status:               string(s.Status),
		ActivePersona:        s.ActivePersona,
		ActiveQueries:        queries,
		TotalQueriesInjected: s.TotalQueriesInjected,
		LastTriggerTime:      s.LastTriggerTime,
		LastError:            s.LastError,
	}
}
